Value(False)
Backend macosx is interactive backend. Turning interactive mode on.
Value(False)
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/gabrielmendessouza/.cursor/extensions/ms-python.debugpy-2024.6.0-darwin-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/gabrielmendessouza/.cursor/extensions/ms-python.debugpy-2024.6.0-darwin-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/gabrielmendessouza/.cursor/extensions/ms-python.debugpy-2024.6.0-darwin-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/gabrielmendessouza/.cursor/extensions/ms-python.debugpy-2024.6.0-darwin-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/gabrielmendessouza/.cursor/extensions/ms-python.debugpy-2024.6.0-darwin-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/gabrielmendessouza/.cursor/extensions/ms-python.debugpy-2024.6.0-darwin-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/Users/gabrielmendessouza/Documents/personal_projects/simple-lenet-classification/src/train.py", line 279, in <module>
    main(args, configs)
  File "/Users/gabrielmendessouza/Documents/personal_projects/simple-lenet-classification/src/train.py", line 239, in main
    train_dataset, val_dataset = create_datasets(configs["root_dir"], transformations)
  File "/Users/gabrielmendessouza/Documents/personal_projects/simple-lenet-classification/src/train.py", line 60, in create_datasets
    train_dataset = CustomImageDataset(f"{root_dir}/train", transform=transform)
  File "/Users/gabrielmendessouza/Documents/personal_projects/simple-lenet-classification/src/train.py", line 36, in __init__
    self.label_map_to_int = {label: i for i, label in enumerate(sorted(set(label for _, label, _ in self.annotations)))}
  File "/Users/gabrielmendessouza/Documents/personal_projects/simple-lenet-classification/src/train.py", line 36, in <genexpr>
    self.label_map_to_int = {label: i for i, label in enumerate(sorted(set(label for _, label, _ in self.annotations)))}
ValueError: too many values to unpack (expected 3)
